include: package:flutter_lints/flutter.yaml
# include: package:surf_lint_rules/analysis_options.yaml

# Custom linter by Surf
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
#   strong-mode:
#     implicit-casts: true
#     implicit-dynamic: true

# sort_pub_dependencies: false

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
