name: fox_quiz
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^3.1.1
  http: ^0.13.5
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  json_annotation: ^4.6.0
  import_sorter: ^4.6.0
  cloud_firestore: ^3.4.4
  firebase_core: ^1.20.1
  freezed_annotation: ^2.1.0
  expandable_page_view: ^1.0.17
  equatable: ^2.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  surf_lint_rules: ^1.5.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
